### ISSUE TITLE
IncompatibleTypes Error in if/else if with assignments

### ISSUE THREAD

**Issue by kbleeke** [untoldwind/KontrolSystem2#105]
I have the following sample code. The function returns Unit and has an if-expression at the end. The code blocks in if and else if simply have assignments as the last expression. 

I expected the type of the `if`-expression to be Unit (like in Rust), however it seems (?) to have a strange interaction with Option creation https://kontrolsystem2.readthedocs.io/en/latest/language/special_types/option.html#creation

This can be circumvented by adding a Unit-expression like {} to the end of each block

```
fn foo() -> Unit = {
    let a: float = 1
    if (true) {
        a = 3
    } else if (true) {
        a = 2
    }
}
```

```
Rebooted in 00:00:01.9058344

ERROR: [test.to2(14, 5)] IncompatibleTypes
If condition has incompatible result float != Option<float>
```

**Comment by untoldwind** [comment]
With the current logic this is kind of correct.

The result of `if (condition) expr1 else expr2` is either the result of `expr1` or `expr2`, which implies that `expr1` and `expr2` have the same type.

The result of `if (condition) expr1` (without else) is `Option<typeof expr1>`.

And since `if (cond1) expr1 else if(cond2) expr2` is read as:
```
if(cond1) {
  expr1
} else {
  if(cond1) {
    expr2
  }
}
```
you get that behavior.
Simple fix would be to add a final `else` branch in your code.

But I admit that this logic is inconvenient, so I probably have to add some logic for `else if` cascades.

**Comment by kbleeke** [comment]
Makes sense. I think what contributed to the confusion on my side was that the result of an assignment is not Unit. 

I guess I can also write it like this:
```
   a = if (true) {
        3
    } else if (true) {
        2
    } else {
        a
    }
```

**Comment by untoldwind** [comment]
Should now work in 0.5.1.1
The result of an `if ... else if ...` (without final `else` fallback) is now an option
