### ISSUE TITLE
Question about console

### ISSUE THREAD

**Issue by lefouvert** [untoldwind/KontrolSystem2#153]
Hi.

What is used for this field and the 3 buttons asides, please ?
![image](https://github.com/untoldwind/KontrolSystem2/assets/57873766/681402f4-b8b3-4fe8-abe8-af7d05d29a7c)

**Comment by untoldwind** [comment]
This is a (so far) pretty under developed feature. The plugin supports running expressions in REPL mode.

So in the text field you can enter something like:
```
ksp::vessel::active_vessel().value.position
```
and run that snippet with the green button. The other buttons are a "command" history.

The text-field is something of a workaround since the console does not support keyboard input (yet ... getting keyboard focus in a reliable way was a big hurdle in the early versions).
Eventually I would like to have that integrated into the console itself, so that you have something akin to a shell (just like in kOS) ... 

... so ... err ... consider it a tech-demo for now ;)

**Comment by lefouvert** [comment]
Thank you !
It already could be usefull in some case.

**Comment by untoldwind** [comment]
In pre-release 0.5.8.0 (https://github.com/untoldwind/KontrolSystem2/releases/tag/v0.5.8.0) this is now part of the console itself. I.e. the console is focusable and has a command prompt.
It is still rather basic and there is a lot of room for further improvements (e.g. it would be nice to have console-input available in scripts as well ... though some internal stuff has to be sorted out for that).
