### ISSUE TITLE
Is it possible to read the user/pilot inputs?

### ISSUE THREAD

**Issue by janismac** [untoldwind/KontrolSystem2#154]
I am looking for the kOS equivalent of this: https://ksp-kos.github.io/KOS/commands/flight/pilot.html

This makes it possible to write fly-by-wire / flight augmentation controllers.

**Comment by untoldwind** [comment]
At the moment this is not part of the API and a lot of the internal FlightInputHandler (that has handling the human input) is private.
But it should be possible to capture the the FlightCtrlState (i.e. the values that actually affect the vessel) before it is "mangled" by any of the autopilots including the builtin SAS ... I have not dug into the code, but I guess that is what kOS is doing as well.

**Comment by untoldwind** [comment]
In pre-release 0.5.7.7 (https://github.com/untoldwind/KontrolSystem2/releases/tag/v0.5.7.7) the Vessel now has a `vessel.pilot_input` that should capture this pilot_input before all the auto-pilots.

Little test program (slightly adapted from another issue):
```
use { Vessel } from ksp::vessel
use { CONSOLE, BLUE, RED, YELLOW, GREEN } from ksp::console
use { DEBUG } from ksp::debug
use { vec3, Vec3, look_dir_up, GlobalVector } from ksp::math
use { sleep, wait_until, wait_while } from ksp::game
use { find_body, Orbit } from ksp::orbit
use { control_steering } from std::control::steering

pub fn main_flight(vessel: Vessel) -> Result<Unit, string> = {
    CONSOLE.clear()


    const frame = vessel.main_body.celestial_frame
    const pointToSunCf = vec3(-3,1,-2).normalized // Anything will do
    const pointToNormal = get_perpendicular(pointToSunCf).normalized

    const sun = find_body("Kerbol")?

    const sunDir = look_dir_up((sun.global_position - vessel.global_position).normalized.to_local(frame), vessel.orbit.orbit_normal.to_global(vessel.orbit.reference_frame).to_local(frame))
    const pointToSunDir = look_dir_up(pointToSunCf.to_global(vessel.control_frame).to_local(frame), pointToNormal.to_global(vessel.control_frame).to_local(frame))
    const rotation = sunDir * pointToSunDir.inverse

    // This takes control over throttle and steering
    const throttle = vessel.set_throttle(0)
    const steering = control_steering(vessel)

    steering.set_direction(rotation * vessel.facing)

    const pi = vessel.pilot_input

    while(true) {
        CONSOLE.clear()
        CONSOLE.print_line($"{pi.pitch} {pi.yaw} {pi.roll}")
        CONSOLE.print_line($"{pi.main_throttle}")
        
        sleep(0.1)
    }
}

sync fn get_perpendicular(v: Vec3) -> Vec3 = if(v.z != 0) vec3(v.z, v.z, -v.x - v.y) else vec3(-v.y-v.z, v.x, v.x)
```

Little quirk: The throttle input of the pilot is not completely ignored, even though `vessel.set_throttle(0)` tries to keep it at `0`.
This is due to the fact, that autopilots are run during a `FixedUpdate` of the Unity engine while throttle input is processed during a regulare `Update` of the engine (without running any autopilots) ... so there is a brief time-window where throttle input by the pilot is actually processed.
I am not sure why it was implemented this way, it might change in future versions of the game.

**Comment by janismac** [comment]
In pre-release 0.5.7.7, it seems to only work when the `vessel.override_input_*` functions are not used. Which unfortunately defeats the purpose. Example:

```
use { Vessel } from ksp::vessel
use { CONSOLE } from ksp::console
use { yield, sleep } from ksp::game

pub fn main_flight(vessel: Vessel) -> Result<Unit> = {
    while(true) {
        CONSOLE.print_line("pilot pitch " + vessel.pilot_input.pitch.to_fixed(2))
        vessel.override_input_pitch(0.5)
        yield()
    }
}
```

This always displays 0.50, it is not influenced by the W and S buttons. Using a longer pause, e.g. with `sleep(0.1)`, makes the final command (as seen on the nav ball) jump back and forth between the script command and pilot command.

**Comment by janismac** [comment]
For now I am using the pilot translate_x,y,z inputs instead. This works as intended:

```
use { Vessel } from ksp::vessel
use { CONSOLE } from ksp::console
use { yield } from ksp::game

pub fn main_flight(vessel: Vessel) -> Result<Unit> = {
    while(true) {
        let angular_vel = vessel.angular_velocity
        let facing      = vessel.facing
        let pitch_rate  = facing.right_vector.dot(angular_vel)
        let yaw_rate    = facing.up_vector.dot(angular_vel)
        let roll_rate   = facing.vector.dot(angular_vel)
        vessel.override_input_pitch(5 * (pitch_rate -  0.1 * vessel.pilot_input.translate_y))
        vessel.override_input_yaw( -5 * (yaw_rate   -  0.1 * vessel.pilot_input.translate_x))
        vessel.override_input_roll( 5 * (roll_rate  -  0.1 * vessel.pilot_input.translate_z))
        yield()
    }
}
```

**Comment by untoldwind** [comment]
This is a tricky one.
Turns out that internally the "override" values are applied before any of the autopilots are called, which makes it nearly impossible to get the original values of the pilot.

So in 0.5.7.8 (https://github.com/untoldwind/KontrolSystem2/releases/tag/v0.5.7.8) I declared the `vessel.override_input_` methods as deprecated. Instead there are corresponding `override_` fields in the `vessel.pilot_input` structure (https://kontrolsystem2.readthedocs.io/en/prerelease/reference/ksp/vessel.html#pilotinput).

All the `override_` are `Option<double>`, i.e. if defined the pilot input is overridden by that value, if undefined (i.e. None) the pilot has control. In either case the other fields (`.pitch`, `.yaw` and so) on should always reflect the pilots input.

A very simple test program:
```
use { Vessel } from ksp::vessel
use { CONSOLE } from ksp::console
use { sleep } from ksp::game

pub fn main_flight(vessel: Vessel) -> Result<Unit, string> = {
    CONSOLE.clear()

    const pi = vessel.pilot_input

    pi.override_yaw = Some(1.0) // yaw is stuck at 1.0

    for(i in 0..100) {
        CONSOLE.clear()
        CONSOLE.print_line($"{pi.pitch} {pi.yaw} {pi.roll}")
        CONSOLE.print_line($"{pi.main_throttle}")
        
        sleep(0.1)
    }

    pi.override_yaw = None() // pilot is has control over yaw again

    while(true) {
        CONSOLE.clear()
        CONSOLE.print_line($"{pi.pitch} {pi.yaw} {pi.roll}")
        CONSOLE.print_line($"{pi.main_throttle}")
        
        sleep(0.1)
    }
}
```

**Comment by untoldwind** [comment]
Should be now part of the 0.5.7.9 release.
