### ISSUE TITLE
Question (not - yet - a request) about Notifications

### ISSUE THREAD

**Issue by PhilouDS** [untoldwind/KontrolSystem2#159]
This is a simple question that went through my mind.
Can we interact with notifications?

![image](https://github.com/untoldwind/KontrolSystem2/assets/77538240/ff4e652d-e056-431d-9bcb-a71cd991c5d9)

Tbh, I'd like an entire mod that get rid of those notifications. They are annoying... But they are there and if we can use Kontrol System to sometimes display a notification, it could be fun.

**Comment by untoldwind** [comment]
This might be either pretty easy or extremely hard.

Internally there is a very nice `NotificationManager`, problem is that it is intertwined with the localization system ... i.e. internally the notifications are a localization-key + parameters  (e.g. in your example above the location-key is "Science/Notifications/ResearchReportSubmitted" and the parameter is 50 ... which is then combined to something readable depending on the selected language).
I am not entirely sure what happens if the localization-key is set to some arbitrary value ... or if there is a special localization-key that allows arbitrary text.

**Comment by untoldwind** [comment]
It actually was rather easy: When using anything as localization-key that is unknown to the LocalizationManager, that text is just used as is.

So in pre-release 0.5.8.0 (https://github.com/untoldwind/KontrolSystem2/releases/tag/v0.5.8.0), this should be possible:
```
use { Vessel } from ksp::vessel
use { notification_alert, notification_passive, Importance } from ksp::game

pub fn main_flight(vessel: Vessel) -> Result<Unit> = {
  notification_alert("Alert title", "Alert message", Importance.Low, 10)
  notification_passive("Passive message")
}
```

Internally there are also "Admin" tier notification, but I did not managed to get them working correctly.

**Comment by PhilouDS** [comment]
Ooh! Thanks for that. More fun is coming :)

**Comment by PhilouDS** [comment]
What's `ksp::game::MESSAGE_BUS` for?

**Comment by PhilouDS** [comment]
![image](https://github.com/untoldwind/KontrolSystem2/assets/77538240/55187582-2ee6-4577-81b0-06d51f931e41)

**Comment by untoldwind** [comment]
> What's `ksp::game::MESSAGE_BUS` for?

I just added a comment about this to this issue: https://github.com/untoldwind/KontrolSystem2/issues/155

> 
> Do you have the new `vsix` file please? I thought the file wasn't needed anymore but I have error from VSC.

I created a fresh one: https://github.com/untoldwind/KontrolSystem2/releases/download/v0.5.8.0/to2-syntax-0.0.48.vsix
... but turns out there are some bugs that prevent the new stuff from being recognized correctly, have to analyze those in more detail.

**Comment by PhilouDS** [comment]
> I created a fresh one: https://github.com/untoldwind/KontrolSystem2/releases/download/v0.5.8.0/to2-syntax-0.0.48.vsix .

I still have an error for the keyword `Importance`

**Comment by untoldwind** [comment]
There where some inconsistencies in the vscode extension. The version in 0.5.8.1 (https://github.com/untoldwind/KontrolSystem2/releases/tag/v0.5.8.1).

There is now an additional setting for the path to the `reference.json` in the KontrolSystem2 addon, this will (hopefully :crossed_fingers: ) make it unnecessary to update the vscode extension with every extension to the API.
