### ISSUE TITLE
Custom unit tests

### ISSUE THREAD

**Issue by versvisa** [untoldwind/KontrolSystem2#161]
Hello, I see there are a bunch of unit test functions of the form `test sync fn test_...() -> Unit = {`. How can I use that system for my own code? When and where are the tests executed?

If it does not happen already, I suppose it would be good to run all tests (optionally) when "rebooting", i.e. loading/compiling the TO2 code.

**Comment by lefouvert** [comment]
issue #120

**Comment by untoldwind** [comment]
As mentioned in the referenced issue, the "test fn" functions are currently only executed during the build process of the addon (as a mix between unit and regression tests).

It would be nice to have this generally available for stuff in "to2Local" as well. There are just some things to consider:
* Adding this to the regular "Reboot" might have some significant impact on performance, so a separate "Run testsuite" button (or similar) would be preferable
  * ... but then there should be also a UI for test results and failures
  * ... and this is a lot of work and just had not enough priority so far ;)
* Event better would be having this integrated into the vscode plugin
  * ... but then there has to be a test-runner
  * ... which in itself is not really all that hard to implement (it would actually be straight forward copy&paste from the XUnit testcases)
  * ... but it would mean, publishing an executable (.exe), which is (rightfully) frowned upon

What I eventually want to explore is, bundling at test-runner as a WASM, so that it could be easily integrated into anything javascript/typescript related and would be executed in a sendbox environment ... but again: Time and priority ;)

**Comment by untoldwind** [comment]
... and sometimes I just overthink it.
pre-release 0.5.8.2 (https://github.com/untoldwind/KontrolSystem2/releases/tag/v0.5.8.2) now has console commands.
One of the commands is "test" to run unit-tests.
* `test` should run all "test fn" that are defined anywhere
* `test <module name>` should just run those of a specific module

Results are reported in the Console window (so no extra UI necessary ;) )

**Comment by untoldwind** [comment]
Now part of the regular release 0.5.8.3

**Comment by lefouvert** [comment]
Gorgeous.
