### ISSUE TITLE
A way to run short one-line scripts

### ISSUE THREAD

**Issue by ThunderousEcho** [untoldwind/KontrolSystem2#22]
Would be useful for entering quick console commands or for Twitch Plays KSP2's.

**Comment by untoldwind** [comment]
I was thinking about this as well.

Right now every script goes to the compiler, essentially becomes an in-memory DLL and is then executed. This is a whole lot for a single-liner ... or a few couple of single-liners.

So maybe there should be an `Eval` on the AST nodes so that you could just run an expression on an existing registry/context.

I will see how much effort that would be.

**Comment by ThunderousEcho** [comment]
Is this something you're still looking into?

**Comment by untoldwind** [comment]
Sorry I should have made this more obvious. I added a Draft-PR for this: #52

Some of the basics are already working, see `REPLBasicTests`.

The reason why this is slightly more complicated is because I wanted to prevent blocking operations, since everything will run as part of the game-loop in the end. So a little four-liner like:
```
let a = 1
while(a > 0) {
  a += 1
}
```
should not block operation

**Comment by ThunderousEcho** [comment]
Sweet, thanks

**Comment by ThunderousEcho** [comment]
I think I've covered all the useful part APIs by now. Is there anything I can do to prepare the mod for REPL?

**Comment by untoldwind** [comment]
The bulk of the ".Eval" has been merged in to the master branch. I had no time tying this to the UI in any useful manner, so any help there would be appreciated.

Currently there is only this clunky code to eval an expression: https://github.com/untoldwind/KontrolSystem2/blob/1cf3331b8d25ddbde68b3e71f374683de94f9fb0/TO2-Test/REPLBasicTests.cs#L151

Though it demonstrate the necessary steps:
* Parse with `TO2ParserREPL.REPLItems.Parse` (or better `.TryParse`)
* Create a `new REPLContext` with an existing registry and `IKSPContext` (both are in the `Mainframe`)
* And then just `.Eval` the expression. The result of this is an `IFuture`, which is a fancy term for an `IEnumerator` that ends at a certain point in the future. 
  * Essentially you can wrap it into a `CorountingAdapter` and then run it in the background of the game, like here: https://github.com/untoldwind/KontrolSystem2/blob/1cf3331b8d25ddbde68b3e71f374683de94f9fb0/SpaceWarpMod/Core/Mainframe.cs#L171

**Comment by ThunderousEcho** [comment]
![image](https://user-images.githubusercontent.com/10161961/228099384-b40f4cc3-cabe-4e44-9f26-f1764acc903d.png)

**Comment by ThunderousEcho** [comment]
@untoldwind Just one thing I noticed with the REPL stuff:
![image](https://user-images.githubusercontent.com/10161961/228110015-3c96eb52-501c-4ae4-88d7-4e659bf30a56.png)

**Comment by untoldwind** [comment]
Yes, I stumbled on that as well. Should work now (`.value` was not returning the correct type information)
