### ISSUE TITLE
Steering override controls inactive during sleep

### ISSUE THREAD

**Issue by SodaPopinski** [untoldwind/KontrolSystem2#37]
I'm not sure if this is by design, but I've found if I use sleep to slow down my functions, the RCS / control surfaces "pulses" instead of staying on, resulting in a choppy attitude adjustment.

Note, in this example code, the override input needs to be in a separate function, otherwise it's too quick without the wait to observe.

use { Vessel, MODE_AUTOPILOT, MODE_STABILITYASSIST } from ksp::vessel
use { CONSOLE } from ksp::console
use { sleep } from ksp::game

pub fn main_flight(vessel: Vessel) -> Result<Unit, string> = {
	vessel.autopilot.mode = MODE_AUTOPILOT
	CONSOLE.print_line("Pitching no sleep")
	
	for (t in 1..300) {
		pitch_craft(vessel,0.5)
	}
	vessel.autopilot.mode = MODE_STABILITYASSIST
	CONSOLE.print_line("Stabililizing")
	for (t in 1..60) {
		sleep(0.1)
	}
	CONSOLE.print_line("Pitching with sleep")
	vessel.autopilot.mode = MODE_AUTOPILOT
	for (t in 1..20) {
		pitch_craft(vessel,0.5)
		sleep(0.5)
	}
	vessel.autopilot.mode = MODE_STABILITYASSIST
	CONSOLE.print_line("Stabililizing")
	for (t in 1..60) {
		sleep(0.1)
	}
}

fn pitch_craft(vessel: Vessel, amount: float) -> Unit = {
    vessel.override_input_pitch(amount)
}

**Comment by untoldwind** [comment]
Not really sure how to address/fix this.

Form what I can see the `FlightInputHandler` works like this:
* The `OverrideInput...` porperties set in internal flag that this value should be used on the next `Fixed update`
* During the `FixedUpdate` that flag is reset to false
* ... so any follow up fixed updates will not use the override any more

The quick fix would probably be to use [yield](https://kontrolsystem2.readthedocs.io/en/latest/interact/async.html#yield) instead of `sleep`, which causes the script to pause until the next `FixedUpdate` (i.e. pretty much the lowest time possible)

A cleaner solution would be to use the steering manager:
```
    const manager = vessel.set_steering(vec3(pitch, yaw, roll)) // now steering is locked to these values

    sleep/wait

    manager.pitch_yaw_roll = vec3(new_pitch, new_yaw, new_rool) // new steering is locked to these values

    sleep/wait
 
   manager.release() // steering control is release
```
or alternatively
``` 
const manager = vessel.manage_steering(fn(deltaT) -> vec3(pitch, yaw, roll))
```
to use a function as calculates flight input on the fly.

The difference is, that internally the `SteeringManager` is an autopilot hook: `OnPreAutopilotUpdate` to be precise, which should happen before SAS does its many things.

**Comment by untoldwind** [comment]
I also looked the into the `VesselComponent.ApplyFlightCtrlState` function, it has pretty much the same problem, i.e. pitch,yaw,roll get reset with each `FixedUpdate`.
So I guess there is no other way but the `manage_steering` method right now.
