### ISSUE TITLE
0.2.0.2: Invalid IL code when updating a structure field

### ISSUE THREAD

**Issue by Farsyte** [untoldwind/KontrolSystem2#47]
This code works:

     const t0 = pick_t0(common)
     common.t0 = t0

But when I wrote it in one line:

     common.t0 = pick_t0(common)

it fails at runtime:

    Invalid IL code in TINKER/AsyncFunction_main_flight:PollValue (): IL_008a: stfld 0x0affc5d1

Relevant portions of `struct Common`:

    pub struct Common(vessel: Vessel) {
        vessel : Vessel = vessel

        t0: float = 0
    }

The `pick_t0` method:

    pub fn pick_t0 (common: Common) -> float = {
        current_time() + 5.0
    }

WORKAROUND: using `pub sync fn pick_t0` avoids the problem.

**Comment by untoldwind** [comment]
Well structs where a somewhat late addition to the language. Originally I wanted to have something purely functional, but sometimes a shared state is so damn useful.

Anyway the problem was that async functions are internally converted to a state-machine, whereas each call to another async function is a state-transition. The variable `common` was put on the stack before the state-transition by the call to `pick_to` function and then tried to be after the transition in the `common.t0` assignment.

**Comment by untoldwind** [comment]
Should work now in 0.2.1

**Comment by untoldwind** [comment]
Closing this for now as it does not have reappeared yet
