### ISSUE TITLE
Fuel transfer implementation?

### ISSUE THREAD

**Issue by SodaPopinski** [untoldwind/KontrolSystem2#60]
Will fuel transfers be implemented?  Hopefully, along with custom name tags for parts?  In kOS, I balance the CoM by transferring fuel between the "forward tank" and "rear tank." It would be great to do that here.

**Comment by untoldwind** [comment]
Yes, that is absolutely on the wishlist.

Unluckily the API is not so obvious. I guess you are supposed to you are supposed to create command entries to the `ResourceFlowRequestBroker` for each part participating in a resource transfer?
Considering that fuel-flow was mentioned on the "to be opimized" list (which seem related), I kept my fingers from this so far ;)

I'll do some deeper digging, but maybe after the next patch when things have stabilized a bit more. Since Asparagus staging is on the todo-list there some further changes to be expected.

**Comment by untoldwind** [comment]
The 0.3.2 version has now a first take on this:

Here is an example script to transfer resources from full tanks to empty tanks (on a test-vessel):
```rust
use { Vessel } from ksp::vessel
use { CONSOLE } from ksp::console
use { current_time, sleep } from ksp::game
use { create_resource_transfer, FlowDirection } from ksp::resource

pub fn main_flight( vessel: Vessel) -> Result<Unit, string> = {
    let rt = create_resource_transfer()

    for(part in vessel.parts) {
        if(part.resources.list.length == 0) continue
        if(part.resources.list[0].stored_units > 5) {
            rt.add_container(FlowDirection.FLOW_OUTBOUND, part.resources)
            CONSOLE.print_line("In>>> " + part.part_name)
        } else {
            rt.add_container(FlowDirection.FLOW_INBOUND, part.resources)
            CONSOLE.print_line("Out>>> " + part.part_name)
        }
    }
    rt.start()

    for(i in 0..100) {
        sleep(0.1)
        CONSOLE.print_line(">> " + rt.is_running.to_string())
    }

    rt.stop()
}
```

**Comment by untoldwind** [comment]
Internally the PartComponent has an `ActivationStage` and `DecoupleStage`. I will check if that is what you are looking for and create a binding for it.
But I noticed that with the current implementation it is possible to create fuel out of nothing. So this needs a bit of rework as well.

**Comment by untoldwind** [comment]
In the 0.3.3 the vessel part now have `activation_stage` and `decouple_stage`, the latter can be negative which means that the part is never decoupled on staging (or at least that is my interpretation of it ;) )

**Comment by PyroSA** [comment]
It looks like KSP2 - 0.1.2 fixed the fuel lines (for the most part) so possibly the 'manual' transfer would be more of a luxury.
Still, the 'unstaged' parts attached to a stage might be handy somewhere.

**Comment by PyroSA** [comment]
The activation_stage and decouple_stage worked nicely. :+1:

The fuel transfer caught me a bit by surprise though.

I expected it to function exactly like the resource transfer in game (only later realizing there's no balance option).

I built a ship with a centre core with a big engine, and several layers of outside tanks with 4-point symmetry.
I set all tanks being decoupled in the next stage to out, and every other tank to in.
Instead of evenly transferring, it was pumping one tank empty at a time. This quickly threw the ship off balance.

**Comment by untoldwind** [comment]
I added a `add_resource` method to the resource transfer: https://kontrolsystem2.readthedocs.io/en/latest/reference/ksp/resource.html#add-resource
With this you can queue the transfer of a specific resource (e.g. from `part.resources.list`) and the maximum number of units to be transfered.

The `ResourceDefinition` (https://kontrolsystem2.readthedocs.io/en/latest/reference/ksp/resource.html#resourcedefinition) also has information about `mass_per_unit` and so on. So it should be possible to do some very fancy resource-balancing

**Comment by PyroSA** [comment]
I've implemented a balanced transfer using the add_resource - much easier to control!

https://gist.github.com/PyroSA/a6dfae059d2483b806876d86273702b5
Fairly clean, so might be worth referencing as a sample...

For my test rocket the transfers seem to all complete in about 1 second, but sometimes still leaves trace amounts.

So this script basically tries to pump Hydrogen, Methane and Oxidizer up as far as possible in the stages.
It repeats roughly every second, and before starting to pump checks if the current stage has run dry - if it has it stages instead of transferring.

I'll have to figure out all these reference frames before I attempt any mass-balancing type scripts.
The asparagus-friendly one works a treat though and works around one of the frustrations - not knowing when it's safe to drop an empty stage.
